#when running container make sure to set port to: anynumber:4200 
FROM node:lts-alpine as build-stage
RUN apk update && apk add bash
RUN mkdir -p /app
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run prod

# production stage

FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /usr/src/app/dist/FrontEnd /usr/share/nginx/html
EXPOSE 4200
CMD ["nginx", "-g", "daemon off;"]
